channels:
- conda-forge
dependencies:
- python=3.12.10
- pip<=25.0.1
- pip:
  - mlflow==3.1.0
  - numpy==2.3.0
  - pandas==2.2.3
  - scikit-learn==1.7.0
  - scipy==1.15.3
  - xgboost==3.0.2
name: mlflow-env
